"""Tests for PR1's origin propagation through promote.py.

`extract_pattern` puts `origin` on the pattern dict; `cluster_and_extract`
keys its return dict by `name` (which now embeds origin via pattern_id);
`write_candidates` must copy `origin` into the staged candidate JSON so
graduate / reopen tooling and PR4's bidirectional reads can route by it.
"""
import json
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "agent" / "memory"))
sys.path.insert(0, str(REPO_ROOT / "agent" / "harness"))

import cluster  # noqa: E402
import promote  # noqa: E402


def _entry(text, *, origin):
    return {
        "timestamp": "2026-04-29T00:00:00+00:00",
        "skill": "test",
        "action": text,
        "reflection": text,
        "detail": text,
        "summary": text,
        "pain_score": 9,
        "importance": 9,
        "origin": origin,
    }


def test_cluster_and_extract_does_not_collide_across_origins(tmp_path):
    """Two clusters with same text but different origins must both
    survive into the cluster_and_extract dict (not overwrite each other)."""
    text = "shared phrase about pnpm package manager"
    entries = (
        [_entry(text, origin="coding.tool_call") for _ in range(3)]
        + [_entry(text, origin="agentry.x.action") for _ in range(3)]
    )
    patterns = promote.cluster_and_extract(entries, threshold=0.3)
    assert len(patterns) == 2
    origins = {p["origin"] for p in patterns.values()}
    assert origins == {"coding.tool_call", "agentry.x.action"}


def test_write_candidates_carries_origin_into_candidate_json(tmp_path):
    text = "agentry-side cluster about reset password"
    entries = [_entry(text, origin="agentry.inbox.action") for _ in range(3)]
    patterns = promote.cluster_and_extract(entries, threshold=0.3)
    assert len(patterns) == 1
    candidates_dir = tmp_path / "candidates"
    candidates_dir.mkdir()
    # Layout the helper expects (semantic dir as sibling of candidates_dir).
    (tmp_path / "semantic").mkdir()
    written = promote.write_candidates(patterns, str(candidates_dir))
    assert written == 1
    files = list(candidates_dir.glob("*.json"))
    assert len(files) == 1
    obj = json.loads(files[0].read_text())
    assert obj["origin"] == "agentry.inbox.action"


def test_write_candidates_default_origin_for_legacy_pattern(tmp_path):
    """A pattern dict missing `origin` (e.g., generated by an older
    extract_pattern path) still gets `coding.tool_call` in the candidate."""
    p = {
        "id": "abcdef123456",
        "name": "pattern_legacy_abc123",
        "claim": "legacy claim",
        "conditions": ["legacy"],
        "evidence_ids": ["2026-01-01T00:00:00Z"],
        "cluster_size": 3,
        "canonical_salience": 8.0,
        # no `origin` key
    }
    candidates_dir = tmp_path / "candidates"
    candidates_dir.mkdir()
    (tmp_path / "semantic").mkdir()
    written = promote.write_candidates({"k": p}, str(candidates_dir))
    assert written == 1
    obj = json.loads((candidates_dir / "abcdef123456.json").read_text())
    assert obj["origin"] == "coding.tool_call"


def test_cluster_and_extract_plumbs_group_by_origin(tmp_path):
    """Opt-out lets a one-off diagnostic pass cluster across origins."""
    text = "shared phrase"
    entries = [
        _entry(text, origin="coding.tool_call"),
        _entry(text, origin="coding.tool_call"),
        _entry(text, origin="agentry.x.action"),
    ]
    grouped = promote.cluster_and_extract(entries, threshold=0.3, group_by_origin=True)
    flat = promote.cluster_and_extract(entries, threshold=0.3, group_by_origin=False)
    # With grouping: only the coding cluster makes it (agentry has 1 entry,
    # below min_size). Without grouping: all three cluster together.
    assert len(grouped) == 1
    assert len(flat) == 1
    # The flat pattern's cluster_size is 3; the grouped one is 2.
    assert next(iter(flat.values()))["cluster_size"] == 3
    assert next(iter(grouped.values()))["cluster_size"] == 2
