"""One-shot cleanup: auto-reject legacy v1 meta-prompt theme.digest candidates.

Pre-PR-#32 versions of theme_cluster.py staged every detected theme as a
candidate with an auto-generated meta-prompt claim ("Recurring topic across
N sessions: <tag>... Review and graduate the durable insight..."). Those
claims aren't behavioral rules and were never graduatable by the user's
standard. The new digester only stages v2 candidates with LLM-synthesized
imperative rules, but legacy v1 candidates sit on disk and clutter the
review queue.

This script clears them in one shot:
  - Walks <brain>/memory/candidates/*.json (and namespaced subdirs)
  - Filters to v1 theme.digest candidates with the meta-prompt claim shape
  - Moves each to candidates/rejected/ via the same `mark_rejected` flow
    that `reject.py` uses, so the audit trail looks identical to a manual
    rejection
  - Records reviewer="prune_legacy_meta_prompts" and a fixed reason

Idempotent: running twice does nothing (already-rejected files don't sit
in the staged scan path). TTY-gated: refuses to run without an interactive
terminal, matching the no-auto-decide contract enforced by
triage_candidates.py.

Usage:
    python3 ~/.agent/tools/prune_legacy_meta_prompts.py [--brain DIR]
    python3 ~/.agent/tools/prune_legacy_meta_prompts.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional


_THIS = Path(__file__).resolve()
sys.path.insert(0, str(_THIS.parent.parent / "memory"))

from review_state import mark_rejected  # type: ignore  # noqa: E402

_NAMESPACES = ("default", "claude-sessions", "codex")

# A candidate is treated as a legacy v1 meta-prompt iff ALL of:
#   - id matches `theme_<hex>` (NOT `theme_v2_<hex>`)
#   - origin == "theme.digest" (not "theme.digest.v2")
#   - status == "staged"
#   - claim starts with "Recurring topic across"
# These were generated by `_theme_claim` in the pre-PR-#32 digester. New
# v2 candidates do not match this shape and stay untouched.
_LEGACY_REVIEWER = "prune_legacy_meta_prompts"
_LEGACY_REASON = (
    "legacy meta-prompt batch cleanup; pre-v2 candidate that never had a "
    "transferable rule. The v2 digester uses LLM-synthesized imperative "
    "claims; these v1 entries predate that filter."
)


def _resolve_brain(arg: Optional[str]) -> Path:
    if arg:
        return Path(arg).expanduser()
    return Path(os.environ.get("BRAIN_ROOT", str(Path.home() / ".agent")))


def _candidate_dir(brain: Path, namespace: str) -> Path:
    if namespace == "default":
        return brain / "memory" / "candidates"
    return brain / "memory" / "candidates" / namespace


def _is_legacy_meta_prompt(data: dict) -> bool:
    cid = data.get("id") or ""
    if not cid.startswith("theme_") or cid.startswith("theme_v2_"):
        return False
    if data.get("origin") != "theme.digest":
        return False
    if data.get("status") != "staged":
        return False
    claim = (data.get("claim") or "").strip().lower()
    return claim.startswith("recurring topic across")


def _collect_legacy(brain: Path) -> list[tuple[str, Path, dict]]:
    """Return [(namespace, candidate_path, data), ...] for every legacy
    meta-prompt currently in any namespace's staged area."""
    out: list[tuple[str, Path, dict]] = []
    for ns in _NAMESPACES:
        cdir = _candidate_dir(brain, ns)
        if not cdir.is_dir():
            continue
        for p in cdir.glob("*.json"):
            if not p.is_file():
                continue
            try:
                data = json.loads(p.read_text())
            except (OSError, json.JSONDecodeError):
                continue
            if _is_legacy_meta_prompt(data):
                out.append((ns, p, data))
    return out


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="prune_legacy_meta_prompts",
        description=__doc__.split("\n")[0],
    )
    p.add_argument("--brain", default=None,
                   help="Brain root (default: $BRAIN_ROOT or ~/.agent).")
    p.add_argument("--dry-run", action="store_true",
                   help="Show what would be rejected; make no changes.")
    p.add_argument("--yes", action="store_true",
                   help="Skip the interactive 'yes' confirmation. Caller "
                        "is asserting they've reviewed the count via "
                        "--dry-run first.")
    args = p.parse_args(argv)

    brain = _resolve_brain(args.brain)
    if not brain.is_dir():
        sys.stderr.write(f"prune: brain not found: {brain}\n")
        return 2

    # TTY check, matching triage_candidates. This script writes to the
    # candidates tree, which is the same surface the no-auto-decide
    # contract protects. An AI assistant invoking us via Bash without a
    # PTY must fail loudly rather than silently move files.
    #
    # --yes does NOT bypass the TTY check. --yes only skips the
    # interactive 'yes to proceed' prompt for a human who has already
    # reviewed the plan via --dry-run. The TTY gate is the structural
    # defense against AI agents and is independent of --yes.
    if not args.dry_run and not sys.stdin.isatty():
        sys.stderr.write(
            "prune: stdin is not a TTY. This script edits the candidates "
            "tree and must be run by a human, not an AI agent via Bash.\n"
            "\n"
            "Use --dry-run from any context to inspect the plan, or run\n"
            "interactively in your own terminal to confirm and apply.\n"
        )
        return 2

    legacy = _collect_legacy(brain)
    if not legacy:
        print(f"prune: nothing to do. No legacy meta-prompt candidates "
              f"found under {brain}.")
        return 0

    by_ns: dict[str, int] = {}
    for ns, _, _ in legacy:
        by_ns[ns] = by_ns.get(ns, 0) + 1

    print()
    print(f"=== legacy meta-prompt cleanup: {len(legacy)} candidate(s) ===")
    for ns, n in by_ns.items():
        print(f"  namespace={ns}: {n}")
    print()
    # Show a handful of sample claims so the user can sanity-check.
    print("sample claims (first 3):")
    for _, path, data in legacy[:3]:
        claim_head = (data.get("claim") or "").strip().replace("\n", " ")[:100]
        print(f"  - {path.name}: {claim_head}...")
    print()

    if args.dry_run:
        print("prune: --dry-run, no changes made.")
        return 0

    if not args.yes:
        try:
            confirm = input(
                f"Reject all {len(legacy)} legacy meta-prompt candidate(s)? "
                "Type 'yes' to proceed: "
            ).strip().lower()
        except EOFError:
            print("\n(eof, aborted)")
            return 0
        if confirm != "yes":
            print("prune: aborted, no changes applied.")
            return 0

    print()
    moved = 0
    failed = 0
    for ns, path, data in legacy:
        cdir = _candidate_dir(brain, ns)
        cid = data.get("id") or path.stem
        try:
            mark_rejected(cid, _LEGACY_REVIEWER, _LEGACY_REASON, str(cdir))
            moved += 1
        except Exception as e:
            sys.stderr.write(f"  WARN {cid}: {type(e).__name__}: {e}\n")
            failed += 1
        if moved % 25 == 0 and moved:
            print(f"  ... {moved}/{len(legacy)} rejected")

    print()
    print(f"prune: total rejected={moved} failed={failed}")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
